// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWycujOGAL4NQtOYS6ARWauFNft2EDMo',
    appId: '1:1031760884192:web:7e1bba632431e378ae3b85',
    messagingSenderId: '1031760884192',
    projectId: 'movilapp-5621c',
    authDomain: 'movilapp-5621c.firebaseapp.com',
    storageBucket: 'movilapp-5621c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rLxJwVsaiZseV21e5dqPqC-NtgUMrc0',
    appId: '1:1031760884192:android:f1f73f34d65a2dd1ae3b85',
    messagingSenderId: '1031760884192',
    projectId: 'movilapp-5621c',
    storageBucket: 'movilapp-5621c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVkyhNP19XV7cKeyicnT-tOFO4K1Warg',
    appId: '1:1031760884192:ios:d991dd29bdf52345ae3b85',
    messagingSenderId: '1031760884192',
    projectId: 'movilapp-5621c',
    storageBucket: 'movilapp-5621c.appspot.com',
    iosClientId: '1031760884192-fmf8h2up98ijvpd8oolup87gc0aiingt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVkyhNP19XV7cKeyicnT-tOFO4K1Warg',
    appId: '1:1031760884192:ios:d991dd29bdf52345ae3b85',
    messagingSenderId: '1031760884192',
    projectId: 'movilapp-5621c',
    storageBucket: 'movilapp-5621c.appspot.com',
    iosClientId: '1031760884192-fmf8h2up98ijvpd8oolup87gc0aiingt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
